### ISSUE TITLE
シリアル通信送信について

### ISSUE THREAD

**Issue by akaikumako** [okayu9/ScrpMotor#3]
Arduinoで読み取ったアナログ値を
シリアル通信でRasPiに送信したいです。
返り値をアナログ値に変更できるように出来ませんか？

**Comment by okayu9** [comment]
アナログ値というのはanalogReadで読み取った値のこと？
だとすれば型はintだから特別なこと無しに送信できるはず．

**Comment by akaikumako** [comment]
そういうことです。具体的にはロータリーエンコーダの値です(^_^;)
MDへの送信はanalogWriteで値が送られているのは分かったのですが、
RaspberryPiへの送信はどうすればいいのでしょうか…?

**Comment by okayu9** [comment]
Raspberry Piへの送信というのは，Raspberry Piからの送信に対する返答ってことでいいのかな．
ScrpMotorを例に取ると，CMDが2のを受信するとdriveMtr1関数が呼ばれる（ようにsetup関数内で設定されている）．
driveMtr1関数内でtx_dataに返答したい値を代入してreturn true;すると，MDDからRaspberry Piにそれが送信される．

つまり，何か値を返したいなら，あるCMDを受け取ったときに呼び出される関数を作って，その関数内で返したい値をtx_dataに格納してreturn true;して，addCMDでその関数を追加すればいい．

**Comment by akaikumako** [comment]
そういうことです！
なるほど、やっと理解できました。
取り敢えずそれでやってみます。
ありがとうございます！
